wandb_version: 1

dropout_rate:
  desc: null
  value: 0
embedding_dimension:
  desc: null
  value: 100
hidden_dimension:
  desc: null
  value: 100
learning_rate:
  desc: null
  value: 0.1
optimizer:
  desc: null
  value: Adam
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.10
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1694798223.888498
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 23
      - 37
      4: 3.10.12
      5: 0.15.10
      8:
      - 1
      - 5
